# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "role_based_authorization"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roberto Esposito"]
  s.date = "2013-05-28"
  s.description = "Provides a simple DSL for specifying the authorization logic of your application. Install the gem, add a role attribute to your user model and your almost ready to go."
  s.email = "boborbt@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/role_based_authorization.rb",
    "lib/role_based_authorization/authorization_logger.rb",
    "lib/role_based_authorization/class_additions.rb",
    "lib/role_based_authorization/role_based_authorization.rb",
    "lib/role_based_authorization/rule.rb",
    "rails/init.rb",
    "role_based_authorization.gemspec",
    "test/authorization_logger_test.rb",
    "test/role_based_authorization_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/boborbt/role_based_authorization"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Basic authorization module for rails"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3"])
      s.add_runtime_dependency(%q<mocha>, ["~> 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3"])
      s.add_dependency(%q<mocha>, ["~> 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3"])
    s.add_dependency(%q<mocha>, ["~> 0"])
  end
end

